---
version: '3'

volumes:
  elasticsearch-data:
    driver: local
  
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/:rw
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.2
    container_name: logstash
    ports:
      - "5959:5959"
    depends_on:
      - elasticsearch
    volumes:
      - ./:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped